-- MySQL Script generated by MySQL Workbench
-- Fri Feb 23 09:47:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smartlab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartlab` ;

-- -----------------------------------------------------
-- Schema smartlab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartlab` DEFAULT CHARACTER SET utf8 ;
USE `smartlab` ;

-- -----------------------------------------------------
-- Table `smartlab`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`user` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`user` (
  `id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `status` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`news` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`news` (
  `id` VARCHAR(20) NOT NULL,
  `content` TEXT NULL,
  `title` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_news_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_news_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `smartlab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`project` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`project` (
  `id` VARCHAR(20) NOT NULL,
  `info` VARCHAR(45) NULL,
  `pm_id` VARCHAR(20) NULL,
  `create_date` DATETIME NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`contest` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`contest` (
  `id` VARCHAR(25) NOT NULL,
  `info` VARCHAR(45) NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`honor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`honor` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`honor` (
  `id` VARCHAR(20) NOT NULL,
  `info` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`document` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`document` (
  `id` VARCHAR(20) NOT NULL,
  `info` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `create_date` DATETIME NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_document_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_document_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `smartlab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`report` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`report` (
  `id` VARCHAR(20) NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `create_date` DATETIME NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_report_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_report_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `smartlab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`project_timeline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`project_timeline` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`project_timeline` (
  `id` INT NOT NULL,
  `create_time` DATETIME NULL,
  `info` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `project_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_project_timeline_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_timeline_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `smartlab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`user_has_contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`user_has_contest` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`user_has_contest` (
  `user_id` VARCHAR(20) NOT NULL,
  `contest_id` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`user_id`, `contest_id`),
  INDEX `fk_user_has_contest_contest1_idx` (`contest_id` ASC),
  INDEX `fk_user_has_contest_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_contest_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `smartlab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_contest_contest1`
    FOREIGN KEY (`contest_id`)
    REFERENCES `smartlab`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`user_has_honor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`user_has_honor` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`user_has_honor` (
  `honor_id` VARCHAR(20) NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`honor_id`, `user_id`),
  INDEX `fk_honor_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_honor_has_user_honor1_idx` (`honor_id` ASC),
  CONSTRAINT `fk_honor_has_user_honor1`
    FOREIGN KEY (`honor_id`)
    REFERENCES `smartlab`.`honor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_honor_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `smartlab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartlab`.`user_has_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartlab`.`user_has_project` ;

CREATE TABLE IF NOT EXISTS `smartlab`.`user_has_project` (
  `project_id` VARCHAR(20) NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`project_id`, `user_id`),
  INDEX `fk_project_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_project_has_user_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_has_user_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `smartlab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `smartlab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
