-- MySQL Script generated by MySQL Workbench
-- Sun Feb 25 22:33:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SmartLab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SmartLab` ;

-- -----------------------------------------------------
-- Schema SmartLab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SmartLab` DEFAULT CHARACTER SET utf8 ;
USE `SmartLab` ;

-- -----------------------------------------------------
-- Table `SmartLab`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`user` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`user` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `status` VARCHAR(20) NULL,
  `user_start` DATETIME NULL,
  `user_leave` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`news` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`news` (
  `id` VARCHAR(32) NOT NULL,
  `content` TEXT NULL,
  `title` VARCHAR(200) NULL,
  `create_date` DATETIME NULL,
  `user_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_news_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_news_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SmartLab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`project` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`project` (
  `id` VARCHAR(32) NOT NULL,
  `info` VARCHAR(200) NULL,
  `create_date` DATETIME NULL,
  `content` TEXT NULL,
  `pmUser_id` VARCHAR(32) NOT NULL,
  `project_progress` INT(20) NULL DEFAULT 0,
  PRIMARY KEY (`id`, `pmUser_id`),
  INDEX `fk_project_user1_idx` (`pmUser_id` ASC),
  CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`pmUser_id`)
    REFERENCES `SmartLab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`contest` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`contest` (
  `id` VARCHAR(32) NOT NULL,
  `info` VARCHAR(200) NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`honor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`honor` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`honor` (
  `id` VARCHAR(32) NOT NULL,
  `info` VARCHAR(200) NULL,
  `content` TEXT NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`document` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`document` (
  `id` VARCHAR(32) NOT NULL,
  `info` VARCHAR(200) NULL,
  `content` TEXT NULL,
  `create_date` DATETIME NULL,
  `user_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_document_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_document_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SmartLab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`report` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`report` (
  `id` VARCHAR(32) NOT NULL,
  `title` VARCHAR(200) NULL,
  `content` TEXT NULL,
  `create_date` DATETIME NULL,
  `user_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_report_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_report_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SmartLab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`project_timeline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`project_timeline` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`project_timeline` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NULL,
  `info` VARCHAR(200) NULL,
  `content` TEXT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_project_timeline_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_timeline_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `SmartLab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`user_has_contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`user_has_contest` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`user_has_contest` (
  `user_id` VARCHAR(32) NOT NULL,
  `contest_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`user_id`, `contest_id`),
  INDEX `fk_user_has_contest_contest1_idx` (`contest_id` ASC),
  INDEX `fk_user_has_contest_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_contest_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SmartLab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_contest_contest1`
    FOREIGN KEY (`contest_id`)
    REFERENCES `SmartLab`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`user_has_honor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`user_has_honor` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`user_has_honor` (
  `honor_id` VARCHAR(32) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`honor_id`, `user_id`),
  INDEX `fk_honor_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_honor_has_user_honor1_idx` (`honor_id` ASC),
  CONSTRAINT `fk_honor_has_user_honor1`
    FOREIGN KEY (`honor_id`)
    REFERENCES `SmartLab`.`honor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_honor_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SmartLab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`user_has_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`user_has_project` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`user_has_project` (
  `project_id` VARCHAR(32) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`project_id`, `user_id`),
  INDEX `fk_project_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_project_has_user_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_has_user_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `SmartLab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SmartLab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmartLab`.`project_member_duty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SmartLab`.`project_member_duty` ;

CREATE TABLE IF NOT EXISTS `SmartLab`.`project_member_duty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `duty_describe` VARCHAR(200) NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `project_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `project_id`),
  INDEX `fk_project_member_duty_user1_idx` (`user_id` ASC),
  INDEX `fk_project_member_duty_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_member_duty_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SmartLab`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_member_duty_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `SmartLab`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
